Ticket 29/chat mes message
bantubeat/featlink_app_ui pull request #34
Opened 2024-08-31 11:38 UTC by BogneStanley

## Ticket link : https://trello.com/c/TioPixz5

# Screenshot

### Pixel 7
![localhost_49853_(Pixel 7)](https://github.com/user-attachments/assets/da481dba-c0fa-4b38-bfeb-091d7e38b48d)

### iPhone SE
![localhost_49853_(iPhone SE)](https://github.com/user-attachments/assets/7250ed27-e799-4aca-9e1b-8fa6f2466325)

### iPad Mini
![localhost_49853_(iPad Mini)](https://github.com/user-attachments/assets/661095c2-7dd3-46cf-a73c-0c9eab0533ea)

2024-09-04 04:49 UTC, Mezatsong requested changes
Le design pour moi est acceptable mais tu as oublié de faire le cas ou l'un des messages est sélectionné

![image](https://github.com/user-attachments/assets/e6cea9bc-4741-4555-bea3-04861e7a08ed)


En plus de cela, ta PR contient trop de modification sur les fichiers qui n'ont rien à voir avec cette PR, surement a cause du linter, je te propose de regler ce pb avec un bon vieux 
- git checkout main
- git pull origin main
- git checkout TA BRANCHE
- git rebase main
- TU GERE LES CONFLITS EN PRENANT LES 2 PARTIES
- git push origin TA BRANCHE --force

EDIT: J'ai fait le rebase déjà

2024-09-04 04:49 UTC, Mezatsong commented on lib/src/screens/_chat_messages/chat_message_list_screen.dart
> +      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
Good job !
J'apprécie le code: 10/10

2024-09-04 04:49 UTC, Mezatsong commented on lib/src/screens/_chat_messages/chat_message_list_screen.dart
> +      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
Pour te recommenpser je vais faire le rebase à ta place

2024-09-04 13:52 UTC, BogneStanley commented on lib/src/screens/_chat_messages/chat_message_list_screen.dart
> +      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
Thanks

2024-09-04 14:40 UTC, BogneStanley commented
Pixel 7
![localhost_58950_(Pixel 7)](https://github.com/user-attachments/assets/eedff9be-c6ed-4903-be9e-bef0765648c7)



iPhone SE
![localhost_58950_(iPhone SE)](https://github.com/user-attachments/assets/3c3bd344-41ba-4292-9a74-005f9cfd4e57)



iPad Mini
![localhost_58950_(iPad Mini)](https://github.com/user-attachments/assets/68a67374-a9c2-4c08-bec3-2b9021ed3dac)

2024-09-04 15:05 UTC, BogneStanley commented
Pixel 7
![localhost_58950_(Pixel 7) (1)](https://github.com/user-attachments/assets/5eca40a1-6b6f-4f5d-92c4-8ba156b97193)



iPhone SE
![localhost_58950_(iPhone SE) (1)](https://github.com/user-attachments/assets/d58980b8-26c1-41b2-a973-84d215cff715)



iPad Mini
![localhost_58950_(iPad Mini) (1)](https://github.com/user-attachments/assets/1ad3f89c-8e28-4152-b1b4-5367a4f1c47a)

2024-09-05 10:55 UTC, Mezatsong approved these changes

2024-09-05 10:56 UTC, merged